### ISSUE TITLE
Why the mark is reduced by nearly half when run the test in docker container.

### ISSUE THREAD

**Issue by cfbsks** [Cyberbolt/py_cpu_test#21]
Generally, the docker container's extra CPU consumption is able to be dismissed.
However, the fact is conflicted.
Specifically, I ran a sysbench test both in docker and in bare machine. The result is almost reduced to half. 

For test, you can use `sudo docker run --rm -it cfbsks/docker-images:alpine python3 app.py`

**Comment by Cyberbolt** [comment]
Yes, it is possible to use Docker in Linux for testing, but Docker for Windows and macOS runs in a virtual machine.

**Comment by cfbsks** [comment]
> Yes, it is possible to use Docker in Linux for testing, but Docker for Windows and macOS runs in a virtual machine.

You might misunderstood what I said. I have already update the issue.

**Comment by Cyberbolt** [comment]
Sorry, I missed this question, is your environment limiting the performance calls of Docker? In the current test list, the 'M1 virtual 虚拟机 Linux' runs with Docker, while the 'M1 macOS' runs natively. The difference between the two is only in multi-core calls, and Docker will not take up all the performance of macOS.

**Comment by Cyberbolt** [comment]
> > Yes, it is possible to use Docker in Linux for testing, but Docker for Windows and macOS runs in a virtual machine.
> 
> You might misunderstood what I said. I have already update the issue.


Sorry, I missed this question, is your environment limiting the performance calls of Docker? In the current test list, the 'M1 虚拟机 Linux' runs with Docker, while the 'M1 macOS' runs natively. The difference between the two is only in multi-core calls, and Docker will not take up all the performance of macOS.

**Comment by cfbsks** [comment]
> > > Yes, it is possible to use Docker in Linux for testing, but Docker for Windows and macOS runs in a virtual machine.
> > 
> > 
> > You might misunderstood what I said. I have already update the issue.
> 
> Sorry, I missed this question, is your environment limiting the performance calls of Docker? In the current test list, the 'M1 虚拟机 Linux' runs with Docker, while the 'M1 macOS' runs natively. The difference between the two is only in multi-core calls, and Docker will not take up all the performance of macOS.

I didnt set any extra limit for Docker, and I tried on the TencentVPS. The point is single-core score under docker was nearly half by bare-machine.

I will try again on my PC, just wait for a few minutes.

**Comment by Cyberbolt** [comment]
> > > > Yes, it is possible to use Docker in Linux for testing, but Docker for Windows and macOS runs in a virtual machine.
> > > 
> > > 
> > > You might misunderstood what I said. I have already update the issue.
> > 
> > 
> > Sorry, I missed this question, is your environment limiting the performance calls of Docker? In the current test list, the 'M1 虚拟机 Linux' runs with Docker, while the 'M1 macOS' runs natively. The difference between the two is only in multi-core calls, and Docker will not take up all the performance of macOS.
> 
> I didnt set any extra limit for Docker, and I tried on the TencentVPS. The point is single-core score under docker was nearly half by bare-machine.
> 
> I will try again on my PC, just wait for a few minutes.

According to our test results, the performance scheduling of Tencent Cloud is very strange, and the multi-core has not exerted its power at all. Please try other hardware platforms.

**Comment by cfbsks** [comment]
> > > > > Yes, it is possible to use Docker in Linux for testing, but Docker for Windows and macOS runs in a virtual machine.
> > > > 
> > > > 
> > > > You might misunderstood what I said. I have already update the issue.
> > > 
> > > 
> > > Sorry, I missed this question, is your environment limiting the performance calls of Docker? In the current test list, the 'M1 虚拟机 Linux' runs with Docker, while the 'M1 macOS' runs natively. The difference between the two is only in multi-core calls, and Docker will not take up all the performance of macOS.
> > 
> > 
> > I didnt set any extra limit for Docker, and I tried on the TencentVPS. The point is single-core score under docker was nearly half by bare-machine.
> > I will try again on my PC, just wait for a few minutes.
> 
> According to our test results, the performance scheduling of Tencent Cloud is very strange, and the multi-core has not exerted its power at all. Please try other hardware platforms.

I tried several tests. We only consider the single-core test.
1. on J1900 bare-machine 68.54% in docker alpine image
2. on E5-2696 v2 bare machine 36.9% in docker alpine image
3. on E5-2696 v2 bare machine 56.7% in docker ubuntu image
4. on Amazon Lightsail 1-core 49.5% in docker alpine image

Confused! 😕

**Comment by Cyberbolt** [comment]
Sorry I wasn't clear either, I don't have this problem on macOS.

**Comment by Cyberbolt** [comment]
I retested M1 with Python 3.10 after upgrading Docker on macOS. Got test scores that surpassed previous ones.
